services:
  database:
    image: postgres:17-alpine3.22
    ports:
      - "5432:5432"
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: testPass
      POSTGRES_DB: testDb
  api:
    build: ./backend
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      PORT: 3000