services:
  database:
    build: ./database
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: testPass
      POSTGRES_DB: testDb
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  front:
    image: httpd:alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend/:/usr/local/apache2/htdocs/:ro