services:
  database:
    build: ./database
    environment:
      POSTGRES_USER: testUser
      POSTGRES_PASSWORD: testPass
      POSTGRES_DB: testDb
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
