
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: matias
      POSTGRES_PASSWORD: matias
      POSTGRES_DB: midb
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql